const ThrowError = () => {
  throw new Error('일반 에러 발생!');
};

export default ThrowError;
